services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb2:/var/lib/influxdb2:rw
    environment: 
       # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myusername
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD:-defaultpassword}
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=temperatures
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-defaulttoken}
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "8086:8086"
    restart: on-failure:10
    networks:
      - influx-grafana-net

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=supersecurepassword
  #   depends_on:
  #     - influxdb
  #   networks:
  #     - influx-grafana-net

# volumes:
#   influxdb-data:
#   grafana-data:

networks:
  influx-grafana-net:
    driver: bridge
